"""Project scaffolding templates for ``workflow-builder init``.

Provides ready-to-use template strings and a helper that computes
which files a ``scaffold_project`` call would create, so the CLI can
preview the result before writing to disk.
"""

from __future__ import annotations

import os
from textwrap import dedent

# ------------------------------------------------------------------
# Template constants
# ------------------------------------------------------------------

QUICKSTART_WORKFLOW: str = dedent("""\
    \"\"\"Example workflow generated by ``workflow-builder init``.\"\"\"

    from __future__ import annotations

    import httpx

    from workflow_builder import Context, Retry, step, workflow


    @step(retry=Retry(max_attempts=3))
    async def fetch_data(ctx: Context, url: str) -> dict:
        \"\"\"Fetch JSON from *url* with automatic retries.\"\"\"
        async with httpx.AsyncClient() as client:
            resp = await client.get(url)
            resp.raise_for_status()
            return resp.json()


    @step()
    async def transform(ctx: Context, data: dict) -> str:
        \"\"\"Return a one-line summary of the fetched data.\"\"\"
        keys = list(data.keys())[:5]
        return f"Keys: {', '.join(keys)}"


    @workflow(name="quickstart")
    async def quickstart_workflow(ctx: Context, url: str) -> str:
        \"\"\"Fetch remote JSON and summarise its top-level keys.\"\"\"
        data = await ctx.step("fetch_data", fetch_data, url=url)
        summary = await ctx.step("transform", transform, data=data)
        return summary
""")

QUICKSTART_TEST: str = dedent("""\
    \"\"\"Tests for the quickstart workflow.\"\"\"

    from __future__ import annotations

    import pytest

    from workflow_builder import Runtime
    from workflow_builder.state.memory import MemoryStore

    from workflows.quickstart import quickstart_workflow


    @pytest.fixture
    def runtime() -> Runtime:
        return Runtime(store=MemoryStore())


    @pytest.mark.asyncio
    async def test_quickstart(runtime: Runtime) -> None:
        result = await runtime.run(
            quickstart_workflow,
            input={"url": "https://httpbin.org/get"},
        )
        assert result.status.value == "completed"
        assert isinstance(result.output, str)
""")

QUICKSTART_PYPROJECT: str = dedent("""\
    [build-system]
    requires = ["setuptools>=75.0"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "my-loom-project"
    version = "0.1.0"
    requires-python = ">=3.11"
    dependencies = [
        "workflow-builder>=0.1",
        "httpx>=0.27",
    ]

    [project.optional-dependencies]
    dev = [
        "pytest>=8.0",
        "pytest-asyncio>=0.24",
    ]

    [tool.pytest.ini_options]
    testpaths = ["tests"]
    asyncio_mode = "auto"

    [tool.ruff]
    target-version = "py311"
    line-length = 100
""")

# ------------------------------------------------------------------
# Lookup helper
# ------------------------------------------------------------------

_TEMPLATES: dict[str, str] = {
    "workflow": QUICKSTART_WORKFLOW,
    "test": QUICKSTART_TEST,
    "pyproject": QUICKSTART_PYPROJECT,
}


def get_template(name: str) -> str | None:
    """Return template content by *name*, or ``None`` if unknown.

    Recognised names: ``"workflow"``, ``"test"``, ``"pyproject"``.
    """
    return _TEMPLATES.get(name)


# ------------------------------------------------------------------
# Scaffold planner
# ------------------------------------------------------------------


def scaffold_project(directory: str) -> list[str]:
    """Return the list of file paths that scaffolding would create.

    The function does **not** write to disk -- it only computes the
    manifest so callers can preview or confirm before committing.
    """
    base = os.path.abspath(directory)
    return [
        os.path.join(base, "pyproject.toml"),
        os.path.join(base, "workflows", "__init__.py"),
        os.path.join(base, "workflows", "quickstart.py"),
        os.path.join(base, "tests", "__init__.py"),
        os.path.join(base, "tests", "test_quickstart.py"),
    ]


__all__ = [
    "QUICKSTART_PYPROJECT",
    "QUICKSTART_TEST",
    "QUICKSTART_WORKFLOW",
    "get_template",
    "scaffold_project",
]
