"""Project scaffolding templates for ``loomsdk init``.

Provides ready-to-use template strings and a helper that computes
which files a ``scaffold_project`` call would create, so the CLI can
preview the result before writing to disk.
"""

from __future__ import annotations

import os
from textwrap import dedent

# ------------------------------------------------------------------
# Template constants
# ------------------------------------------------------------------

QUICKSTART_WORKFLOW: str = dedent('''\
    """Example workflow generated by ``loom init``.

    Two rules carry most of the value:

    1. All I/O happens inside a ``@step``, never in the workflow body.
    2. The workflow body reaches the outside world only through ``ctx``.

    Together they are what let a run resume after a crash without repeating
    work it already did.
    """

    from __future__ import annotations

    from loom import Context, Retry, step, workflow

    # A stand-in for whatever you actually call. Swap the body for an httpx
    # request and the workflow around it does not change.
    _RECORDS = {
        "alice": {"name": "Alice", "plan": "pro", "seats": 12},
        "bob": {"name": "Bob", "plan": "free", "seats": 1},
    }


    @step(retry=Retry(max_attempts=3))
    async def fetch_account(account_id: str) -> dict:
        """Look up an account. Retried three times on failure."""
        record = _RECORDS.get(account_id)
        if record is None:
            raise KeyError(f"no account {account_id!r}")
        return record


    @step
    async def summarise(account: dict) -> str:
        """Turn an account record into a one-line summary."""
        return f"{account['name']} is on {account['plan']} with {account['seats']} seat(s)"


    @workflow(name="quickstart")
    async def quickstart_workflow(ctx: Context, account_id: str) -> str:
        """Fetch an account and summarise it."""
        account = await ctx.step(fetch_account, account_id)
        return await ctx.step(summarise, account)


    if __name__ == "__main__":
        import asyncio

        from loom import Runtime

        async def main() -> None:
            # The store comes from $LOOM_STORE and defaults to in-memory. This
            # module never picks one: where the journal lives is a deployment
            # decision, so the same workflow runs in a test, on a laptop, and
            # in production unchanged.
            #
            #     LOOM_STORE=sqlite://runs.db python workflows/quickstart.py
            result = await Runtime.from_env().run(quickstart_workflow, "alice")
            print(f"{result.status.value}: {result.output}")

        asyncio.run(main())
''')

QUICKSTART_TEST: str = dedent('''\
    """Tests for the quickstart workflow.

    Runs against ``MemoryStore``, so the whole durable-execution engine is
    exercised with no infrastructure at all.
    """

    from __future__ import annotations

    import pytest

    from loom import ExecutionStatus, Runtime
    from loom.stores.memory import MemoryStore

    from workflows.quickstart import quickstart_workflow


    @pytest.fixture
    def runtime() -> Runtime:
        return Runtime(store=MemoryStore())


    async def test_quickstart(runtime: Runtime) -> None:
        result = await runtime.run(quickstart_workflow, "alice")

        assert result.status is ExecutionStatus.COMPLETED
        assert result.output == "Alice is on pro with 12 seat(s)"


    async def test_unknown_account_fails(runtime: Runtime) -> None:
        result = await runtime.run(quickstart_workflow, "nobody")

        assert result.status is ExecutionStatus.FAILED
        assert "nobody" in result.error.message


    async def test_replay_reuses_recorded_results(runtime: Runtime) -> None:
        """Replay serves every step from the journal — no work is repeated."""
        first = await runtime.run(quickstart_workflow, "bob")
        replayed = await runtime.replay(first.run_id)

        assert replayed.status is ExecutionStatus.COMPLETED
        assert replayed.output == first.output
''')

QUICKSTART_PYPROJECT: str = dedent("""\
    [build-system]
    requires = ["setuptools>=75.0"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "my-loom-project"
    version = "0.1.0"
    requires-python = ">=3.11"
    dependencies = [
        "loomsdk>=0.1",
        "httpx>=0.27",
    ]

    [project.optional-dependencies]
    dev = [
        "pytest>=8.0",
        "pytest-asyncio>=0.24",
    ]

    # Where `loom` looks for workflows when you name one without a path, so
    # `loom run quickstart` works and `loom approve <run> <subject>` can find
    # the code to resume. Add a line per file as the project grows.
    [tool.loom]
    modules = ["workflows/quickstart.py"]

    # Where runs are kept. Left commented because the default is already
    # right for a project: `.loom/runs.db` beside this file, so a run you
    # start in one command is there for `loom runs`, `loom watch` and
    # `loom approve` in the next. Set it when the journal should live
    # somewhere shared instead.
    #
    #   store = "postgres://user@host/loom"
    #
    # $LOOM_STORE overrides this, and `--store` overrides both.

    [tool.pytest.ini_options]
    testpaths = ["tests"]
    asyncio_mode = "auto"

    [tool.ruff]
    target-version = "py311"
    line-length = 100
""")


QUICKSTART_GITIGNORE: str = dedent("""\
    # Loom keeps this project's run journal here. It is derived state — the
    # workflows are the source of truth — so it is ignored the way .venv is.
    .loom/

    # Secrets. `loom` reads this file, so a provider key put here is picked up
    # by `loom author` without exporting anything.
    .env

    __pycache__/
    *.py[cod]
    .venv/
    .pytest_cache/
""")

QUICKSTART_ENV_EXAMPLE: str = dedent("""\
    # Copy to `.env`. Loom reads it from the project root, and a real
    # environment variable always wins over a line here.

    # Authoring needs one of these. `loom author` and `loom edit` refuse
    # without it, and so does any workflow calling ctx.agent().
    # ANTHROPIC_API_KEY=
    # OPENAI_API_KEY=
    # GEMINI_API_KEY=

    # Where runs are kept. Unset, they go to .loom/runs.db beside
    # pyproject.toml, which is what you want on a laptop.
    # LOOM_STORE=postgres://user@host/loom
""")

# ------------------------------------------------------------------
# Lookup helper
# ------------------------------------------------------------------

_TEMPLATES: dict[str, str] = {
    "workflow": QUICKSTART_WORKFLOW,
    "test": QUICKSTART_TEST,
    "pyproject": QUICKSTART_PYPROJECT,
    "gitignore": QUICKSTART_GITIGNORE,
    "env": QUICKSTART_ENV_EXAMPLE,
}


def get_template(name: str) -> str | None:
    """Return template content by *name*, or ``None`` if unknown.

    Recognised names: ``"workflow"``, ``"test"``, ``"pyproject"``,
    ``"gitignore"``, ``"env"``.
    """
    return _TEMPLATES.get(name)


# ------------------------------------------------------------------
# Scaffold planner
# ------------------------------------------------------------------


def scaffold_project(directory: str) -> list[str]:
    """Return the list of file paths that scaffolding would create.

    The function does **not** write to disk -- it only computes the
    manifest so callers can preview or confirm before committing.
    """
    return list(_contents(directory))


def write_project(directory: str) -> list[str]:
    """Create the project skeleton on disk and return the paths written.

    Existing files are left alone rather than overwritten — scaffolding into a
    directory someone has already worked in should be additive, never
    destructive.
    """
    written: list[str] = []
    for target, body in _contents(directory).items():
        if os.path.exists(target):
            continue
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(body)
        written.append(target)
    return written


def _contents(directory: str) -> dict[str, str]:
    """Absolute path to body, for every file a scaffold writes.

    One definition, so the preview and the write cannot disagree about what a
    scaffold contains — which is the only way ``--dry-run`` is worth anything.
    """
    base = os.path.abspath(directory)
    return {
        os.path.join(base, relative): body
        for relative, body in {
            "pyproject.toml": QUICKSTART_PYPROJECT,
            # Both are what makes the scaffolded project actually work: `.env`
            # is where a provider key goes and `loom` reads it, and `.gitignore`
            # is what keeps the run journal — derived state — out of the commit.
            ".gitignore": QUICKSTART_GITIGNORE,
            ".env.example": QUICKSTART_ENV_EXAMPLE,
            os.path.join("workflows", "__init__.py"): "",
            os.path.join("workflows", "quickstart.py"): QUICKSTART_WORKFLOW,
            os.path.join("tests", "__init__.py"): "",
            os.path.join("tests", "test_quickstart.py"): QUICKSTART_TEST,
        }.items()
    }


__all__ = [
    "QUICKSTART_ENV_EXAMPLE",
    "QUICKSTART_GITIGNORE",
    "QUICKSTART_PYPROJECT",
    "QUICKSTART_TEST",
    "QUICKSTART_WORKFLOW",
    "get_template",
    "scaffold_project",
    "write_project",
]
